// GENERATED by `npm run landing:assets` (scripts/publish-landing-assets.mjs) from
// the gallery capture's own record. Do not edit by hand: re-record instead.
//
// The gallery's recorded loops, keyed by the `data-media` of the box each one
// plays in (index.html): every rendition the page may choose between
// (src/vitrine/renditions.js). A box with no entry keeps its still.
export const GALLERY_LOOPS = Object.freeze({
  "capturedAt": "2026-09-19T14:20:07.440Z",
  "loops": {
    "view:01": {
      "aspect": 1.66,
      "fps": 30,
      "durationS": 6,
      "renditions": [
        {
          "src": "/landing/view-01-480-av1.8684f052.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 480,
          "height": 290,
          "bytes": 26357,
          "bitrateKbps": 35
        },
        {
          "src": "/landing/view-01-480-h264.5bf9f764.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 480,
          "height": 290,
          "bytes": 30931,
          "bitrateKbps": 41
        },
        {
          "src": "/landing/view-01-960-av1.ea6aaf39.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 582,
          "bytes": 70723,
          "bitrateKbps": 94
        },
        {
          "src": "/landing/view-01-960-h264.687627ea.mp4",
          "mime": "video/mp4; codecs=\"avc1.64001F\"",
          "codec": "h264",
          "width": 960,
          "height": 582,
          "bytes": 88745,
          "bitrateKbps": 118
        },
        {
          "src": "/landing/view-01-1440-av1.e9d56038.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1440,
          "height": 872,
          "bytes": 126663,
          "bitrateKbps": 169
        }
      ]
    },
    "view:02": {
      "aspect": 1.66,
      "fps": 30,
      "durationS": 6,
      "renditions": [
        {
          "src": "/landing/view-02-480-av1.bf75f859.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 480,
          "height": 290,
          "bytes": 51532,
          "bitrateKbps": 69
        },
        {
          "src": "/landing/view-02-480-h264.1ce878e0.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 480,
          "height": 290,
          "bytes": 278798,
          "bitrateKbps": 372
        },
        {
          "src": "/landing/view-02-960-av1.dcf9c9e9.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 582,
          "bytes": 299676,
          "bitrateKbps": 400
        },
        {
          "src": "/landing/view-02-960-h264.11a3d65e.mp4",
          "mime": "video/mp4; codecs=\"avc1.64001F\"",
          "codec": "h264",
          "width": 960,
          "height": 582,
          "bytes": 651091,
          "bitrateKbps": 868
        },
        {
          "src": "/landing/view-02-1440-av1.f821295b.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1440,
          "height": 872,
          "bytes": 929273,
          "bitrateKbps": 1239
        }
      ]
    },
    "view:03": {
      "aspect": 1.66,
      "fps": 30,
      "durationS": 6,
      "renditions": [
        {
          "src": "/landing/view-03-480-av1.8120eecc.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 480,
          "height": 290,
          "bytes": 58365,
          "bitrateKbps": 78
        },
        {
          "src": "/landing/view-03-480-h264.bb91e8f6.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 480,
          "height": 290,
          "bytes": 124416,
          "bitrateKbps": 166
        },
        {
          "src": "/landing/view-03-960-av1.46fdcc7b.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 582,
          "bytes": 193754,
          "bitrateKbps": 258
        },
        {
          "src": "/landing/view-03-960-h264.0e7ef634.mp4",
          "mime": "video/mp4; codecs=\"avc1.64001F\"",
          "codec": "h264",
          "width": 960,
          "height": 582,
          "bytes": 587459,
          "bitrateKbps": 783
        },
        {
          "src": "/landing/view-03-1440-av1.478d7303.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1440,
          "height": 872,
          "bytes": 398664,
          "bitrateKbps": 532
        }
      ]
    },
    "view:04": {
      "aspect": 1.66,
      "fps": 30,
      "durationS": 6,
      "renditions": [
        {
          "src": "/landing/view-04-480-av1.6e79d5ce.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 480,
          "height": 290,
          "bytes": 69610,
          "bitrateKbps": 93
        },
        {
          "src": "/landing/view-04-480-h264.46252b9d.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 480,
          "height": 290,
          "bytes": 273904,
          "bitrateKbps": 365
        },
        {
          "src": "/landing/view-04-960-av1.9ec9d3bb.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 582,
          "bytes": 195929,
          "bitrateKbps": 261
        },
        {
          "src": "/landing/view-04-960-h264.06e5c35a.mp4",
          "mime": "video/mp4; codecs=\"avc1.64001F\"",
          "codec": "h264",
          "width": 960,
          "height": 582,
          "bytes": 459398,
          "bitrateKbps": 613
        },
        {
          "src": "/landing/view-04-1440-av1.26f0d31b.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1440,
          "height": 872,
          "bytes": 498484,
          "bitrateKbps": 665
        }
      ]
    },
    "view:05": {
      "aspect": 1.66,
      "fps": 30,
      "durationS": 6,
      "renditions": [
        {
          "src": "/landing/view-05-480-av1.d874c4b3.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 480,
          "height": 290,
          "bytes": 40998,
          "bitrateKbps": 55
        },
        {
          "src": "/landing/view-05-480-h264.431d60d8.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 480,
          "height": 290,
          "bytes": 65888,
          "bitrateKbps": 88
        },
        {
          "src": "/landing/view-05-960-av1.fe9dbefa.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 582,
          "bytes": 131871,
          "bitrateKbps": 176
        },
        {
          "src": "/landing/view-05-960-h264.4e098847.mp4",
          "mime": "video/mp4; codecs=\"avc1.64001F\"",
          "codec": "h264",
          "width": 960,
          "height": 582,
          "bytes": 215982,
          "bitrateKbps": 288
        },
        {
          "src": "/landing/view-05-1440-av1.0adcc6ee.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1440,
          "height": 872,
          "bytes": 240077,
          "bitrateKbps": 320
        }
      ]
    },
    "view:06": {
      "aspect": 1.66,
      "fps": 30,
      "durationS": 6,
      "renditions": [
        {
          "src": "/landing/view-06-480-av1.9c8bb946.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 480,
          "height": 290,
          "bytes": 51642,
          "bitrateKbps": 69
        },
        {
          "src": "/landing/view-06-480-h264.16eeeb05.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 480,
          "height": 290,
          "bytes": 278497,
          "bitrateKbps": 371
        },
        {
          "src": "/landing/view-06-960-av1.1d68a79d.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 582,
          "bytes": 135313,
          "bitrateKbps": 180
        },
        {
          "src": "/landing/view-06-960-h264.153a3cdd.mp4",
          "mime": "video/mp4; codecs=\"avc1.64001F\"",
          "codec": "h264",
          "width": 960,
          "height": 582,
          "bytes": 408040,
          "bitrateKbps": 544
        },
        {
          "src": "/landing/view-06-1440-av1.881f0d61.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1440,
          "height": 872,
          "bytes": 277776,
          "bitrateKbps": 370
        }
      ]
    },
    "voice-response": {
      "aspect": 2.91,
      "fps": 30,
      "durationS": 6,
      "renditions": [
        {
          "src": "/landing/voice-bus-600-av1.9643e64f.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 600,
          "height": 206,
          "bytes": 48527,
          "bitrateKbps": 65
        },
        {
          "src": "/landing/voice-bus-600-h264.11eaa0c5.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 600,
          "height": 206,
          "bytes": 86234,
          "bitrateKbps": 115
        },
        {
          "src": "/landing/voice-bus-1200-av1.d1061e4b.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 1200,
          "height": 414,
          "bytes": 143632,
          "bitrateKbps": 192
        },
        {
          "src": "/landing/voice-bus-1200-h264.2090e6fd.mp4",
          "mime": "video/mp4; codecs=\"avc1.64001F\"",
          "codec": "h264",
          "width": 1200,
          "height": 414,
          "bytes": 247007,
          "bitrateKbps": 329
        }
      ]
    }
  }
});
