// GENERATED by `npm run landing:assets` (scripts/publish-landing-assets.mjs) from
// the gallery capture's own record. Do not edit by hand: re-record instead.
//
// The gallery's recorded loops, keyed by the `data-media` of the box each one
// plays in (index.html): every rendition the page may choose between
// (src/vitrine/renditions.js). A box with no entry keeps its still.
export const GALLERY_LOOPS = Object.freeze({
  "capturedAt": "2026-09-21T13:52:46.981Z",
  "loops": {
    "view:01": {
      "aspect": 1.66,
      "fps": 30,
      "durationS": 28.97,
      "renditions": [
        {
          "src": "/landing/view-01-480-av1.9e3bd6b9.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 480,
          "height": 290,
          "bytes": 1160937,
          "bitrateKbps": 321
        },
        {
          "src": "/landing/view-01-480-hevc.9f473a08.mp4",
          "mime": "video/mp4; codecs=\"hvc1.1.6.L63.90\"",
          "codec": "hevc",
          "width": 480,
          "height": 290,
          "bytes": 1211697,
          "bitrateKbps": 335
        },
        {
          "src": "/landing/view-01-480-h264.dd216200.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 480,
          "height": 290,
          "bytes": 1410720,
          "bitrateKbps": 390
        },
        {
          "src": "/landing/view-01-960-av1.f5d8f0d8.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 582,
          "bytes": 2827557,
          "bitrateKbps": 781
        },
        {
          "src": "/landing/view-01-960-hevc.9669d981.mp4",
          "mime": "video/mp4; codecs=\"hvc1.1.6.L93.90\"",
          "codec": "hevc",
          "width": 960,
          "height": 582,
          "bytes": 3805706,
          "bitrateKbps": 1051
        },
        {
          "src": "/landing/view-01-1440-av1.d1c27613.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1440,
          "height": 872,
          "bytes": 5216585,
          "bitrateKbps": 1441
        },
        {
          "src": "/landing/view-01-1440-hevc.fd37e1a5.mp4",
          "mime": "video/mp4; codecs=\"hvc1.1.6.L120.90\"",
          "codec": "hevc",
          "width": 1440,
          "height": 872,
          "bytes": 7583972,
          "bitrateKbps": 2095
        }
      ]
    },
    "view:02": {
      "aspect": 1.66,
      "fps": 30,
      "durationS": 6,
      "renditions": [
        {
          "src": "/landing/view-02-480-av1.bf75f859.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 480,
          "height": 290,
          "bytes": 51532,
          "bitrateKbps": 69
        },
        {
          "src": "/landing/view-02-480-h264.1ce878e0.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 480,
          "height": 290,
          "bytes": 278798,
          "bitrateKbps": 372
        },
        {
          "src": "/landing/view-02-960-av1.dcf9c9e9.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 582,
          "bytes": 299676,
          "bitrateKbps": 400
        },
        {
          "src": "/landing/view-02-960-h264.11a3d65e.mp4",
          "mime": "video/mp4; codecs=\"avc1.64001F\"",
          "codec": "h264",
          "width": 960,
          "height": 582,
          "bytes": 651091,
          "bitrateKbps": 868
        },
        {
          "src": "/landing/view-02-1440-av1.f821295b.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1440,
          "height": 872,
          "bytes": 929273,
          "bitrateKbps": 1239
        }
      ]
    },
    "view:03": {
      "aspect": 1.66,
      "fps": 30,
      "durationS": 6,
      "renditions": [
        {
          "src": "/landing/view-03-480-av1.8120eecc.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 480,
          "height": 290,
          "bytes": 58365,
          "bitrateKbps": 78
        },
        {
          "src": "/landing/view-03-480-h264.bb91e8f6.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 480,
          "height": 290,
          "bytes": 124416,
          "bitrateKbps": 166
        },
        {
          "src": "/landing/view-03-960-av1.46fdcc7b.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 582,
          "bytes": 193754,
          "bitrateKbps": 258
        },
        {
          "src": "/landing/view-03-960-h264.0e7ef634.mp4",
          "mime": "video/mp4; codecs=\"avc1.64001F\"",
          "codec": "h264",
          "width": 960,
          "height": 582,
          "bytes": 587459,
          "bitrateKbps": 783
        },
        {
          "src": "/landing/view-03-1440-av1.478d7303.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1440,
          "height": 872,
          "bytes": 398664,
          "bitrateKbps": 532
        }
      ]
    },
    "view:04": {
      "aspect": 1.66,
      "fps": 30,
      "durationS": 14.67,
      "openingS": 11.67,
      "renditions": [
        {
          "src": "/landing/view-04-480-av1.079ac161.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 480,
          "height": 290,
          "bytes": 344611,
          "bitrateKbps": 188
        },
        {
          "src": "/landing/view-04-480-hevc.a01e06ac.mp4",
          "mime": "video/mp4; codecs=\"hvc1.1.6.L63.90\"",
          "codec": "hevc",
          "width": 480,
          "height": 290,
          "bytes": 474003,
          "bitrateKbps": 259
        },
        {
          "src": "/landing/view-04-480-h264.38a7357d.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 480,
          "height": 290,
          "bytes": 545299,
          "bitrateKbps": 297
        },
        {
          "src": "/landing/view-04-960-av1.fc174c4d.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 582,
          "bytes": 773017,
          "bitrateKbps": 422
        },
        {
          "src": "/landing/view-04-960-hevc.c5513ffd.mp4",
          "mime": "video/mp4; codecs=\"hvc1.1.6.L93.90\"",
          "codec": "hevc",
          "width": 960,
          "height": 582,
          "bytes": 1371153,
          "bitrateKbps": 748
        },
        {
          "src": "/landing/view-04-1440-av1.518d6bbc.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1440,
          "height": 872,
          "bytes": 1776432,
          "bitrateKbps": 969
        },
        {
          "src": "/landing/view-04-1440-hevc.4cce6f4f.mp4",
          "mime": "video/mp4; codecs=\"hvc1.1.6.L120.90\"",
          "codec": "hevc",
          "width": 1440,
          "height": 872,
          "bytes": 2745049,
          "bitrateKbps": 1497
        }
      ]
    },
    "view:05": {
      "aspect": 1.66,
      "fps": 30,
      "durationS": 6,
      "renditions": [
        {
          "src": "/landing/view-05-480-av1.d874c4b3.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 480,
          "height": 290,
          "bytes": 40998,
          "bitrateKbps": 55
        },
        {
          "src": "/landing/view-05-480-h264.431d60d8.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 480,
          "height": 290,
          "bytes": 65888,
          "bitrateKbps": 88
        },
        {
          "src": "/landing/view-05-960-av1.fe9dbefa.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 582,
          "bytes": 131871,
          "bitrateKbps": 176
        },
        {
          "src": "/landing/view-05-960-h264.4e098847.mp4",
          "mime": "video/mp4; codecs=\"avc1.64001F\"",
          "codec": "h264",
          "width": 960,
          "height": 582,
          "bytes": 215982,
          "bitrateKbps": 288
        },
        {
          "src": "/landing/view-05-1440-av1.0adcc6ee.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1440,
          "height": 872,
          "bytes": 240077,
          "bitrateKbps": 320
        }
      ]
    },
    "view:06": {
      "aspect": 1.66,
      "fps": 30,
      "durationS": 6,
      "renditions": [
        {
          "src": "/landing/view-06-480-av1.9c8bb946.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 480,
          "height": 290,
          "bytes": 51642,
          "bitrateKbps": 69
        },
        {
          "src": "/landing/view-06-480-h264.16eeeb05.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 480,
          "height": 290,
          "bytes": 278497,
          "bitrateKbps": 371
        },
        {
          "src": "/landing/view-06-960-av1.1d68a79d.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 582,
          "bytes": 135313,
          "bitrateKbps": 180
        },
        {
          "src": "/landing/view-06-960-h264.153a3cdd.mp4",
          "mime": "video/mp4; codecs=\"avc1.64001F\"",
          "codec": "h264",
          "width": 960,
          "height": 582,
          "bytes": 408040,
          "bitrateKbps": 544
        },
        {
          "src": "/landing/view-06-1440-av1.881f0d61.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1440,
          "height": 872,
          "bytes": 277776,
          "bitrateKbps": 370
        }
      ]
    },
    "voice-response": {
      "aspect": 2.91,
      "fps": 30,
      "durationS": 6,
      "renditions": [
        {
          "src": "/landing/voice-bus-600-av1.9643e64f.mp4",
          "mime": "video/mp4; codecs=\"av01.0.00M.08\"",
          "codec": "av1",
          "width": 600,
          "height": 206,
          "bytes": 48527,
          "bitrateKbps": 65
        },
        {
          "src": "/landing/voice-bus-600-h264.11eaa0c5.mp4",
          "mime": "video/mp4; codecs=\"avc1.640015\"",
          "codec": "h264",
          "width": 600,
          "height": 206,
          "bytes": 86234,
          "bitrateKbps": 115
        },
        {
          "src": "/landing/voice-bus-1200-av1.d1061e4b.mp4",
          "mime": "video/mp4; codecs=\"av01.0.04M.08\"",
          "codec": "av1",
          "width": 1200,
          "height": 414,
          "bytes": 143632,
          "bitrateKbps": 192
        },
        {
          "src": "/landing/voice-bus-1200-h264.2090e6fd.mp4",
          "mime": "video/mp4; codecs=\"avc1.64001F\"",
          "codec": "h264",
          "width": 1200,
          "height": 414,
          "bytes": 247007,
          "bitrateKbps": 329
        }
      ]
    }
  }
});
