// GENERATED by `npm run landing:assets` (scripts/publish-landing-assets.mjs) from
// the capture's own record. Do not edit by hand: re-record instead.
//
// The recorded hero loops: every rendition the page may choose between
// (src/vitrine/renditions.js), and the camera law each loop was filmed with,
// which src/vitrine/handoff.js evaluates at the video's clock.
export const HERO_LOOP = Object.freeze({
  "capturedAt": "2026-09-17T16:16:42.164Z",
  "videos": {
    "desktop": {
      "aspect": 1.6,
      "fps": 30,
      "durationS": 18,
      "orbit": {
        "centerLat": 48.83258059769346,
        "centerLon": 2.264310753270303,
        "centerHeight": 95.26787844651355,
        "rangeM": 582.8220426184888,
        "pitchDeg": -59.997394702801266,
        "headingStartDeg": 349.99947886731456,
        "amplitudeDeg": 8,
        "periodS": 18,
        "law": "cosine"
      },
      "renditions": [
        {
          "src": "/landing/hero-desktop-2880-av1.b8811f4c.mp4",
          "mime": "video/mp4; codecs=\"av01.0.12M.08\"",
          "codec": "av1",
          "width": 2880,
          "height": 1800,
          "bytes": 13934293,
          "bitrateKbps": 6193
        },
        {
          "src": "/landing/hero-desktop-2880-hevc.21bc091c.mp4",
          "mime": "video/mp4; codecs=\"hvc1.1.6.L150.90\"",
          "codec": "hevc",
          "width": 2880,
          "height": 1800,
          "bytes": 13023483,
          "bitrateKbps": 5788
        },
        {
          "src": "/landing/hero-desktop-1920-av1.472dca66.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1920,
          "height": 1200,
          "bytes": 7556857,
          "bitrateKbps": 3359
        },
        {
          "src": "/landing/hero-desktop-1920-h264.f3001358.mp4",
          "mime": "video/mp4; codecs=\"avc1.640032\"",
          "codec": "h264",
          "width": 1920,
          "height": 1200,
          "bytes": 11427022,
          "bitrateKbps": 5079
        }
      ]
    },
    "phone": {
      "aspect": 0.461983,
      "fps": 30,
      "durationS": 18,
      "orbit": {
        "centerLat": 48.83258058872229,
        "centerLon": 2.264310755666521,
        "centerHeight": 95.2696329328622,
        "rangeM": 582.8200166586506,
        "pitchDeg": -59.99739471184423,
        "headingStartDeg": 349.9994788691313,
        "amplitudeDeg": 8,
        "periodS": 18,
        "law": "cosine"
      },
      "renditions": [
        {
          "src": "/landing/hero-phone-960-av1.a43a8bfd.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 2078,
          "bytes": 5472563,
          "bitrateKbps": 2432
        },
        {
          "src": "/landing/hero-phone-960-hevc.c683043a.mp4",
          "mime": "video/mp4; codecs=\"hvc1.1.6.L120.90\"",
          "codec": "hevc",
          "width": 960,
          "height": 2078,
          "bytes": 5319289,
          "bitrateKbps": 2364
        }
      ]
    }
  }
});
