// GENERATED by `npm run landing:assets` (scripts/publish-landing-assets.mjs) from
// the capture's own record. Do not edit by hand: re-record instead.
//
// The recorded hero loops: every rendition the page may choose between
// (src/vitrine/renditions.js), and the camera law each loop was filmed with,
// which src/vitrine/handoff.js evaluates at the video's clock.
export const HERO_LOOP = Object.freeze({
  "capturedAt": "2026-09-17T16:16:42.164Z",
  "videos": {
    "desktop": {
      "aspect": 1.6,
      "fps": 30,
      "durationS": 18,
      "orbit": {
        "centerLat": 48.83258059769346,
        "centerLon": 2.264310753270303,
        "centerHeight": 95.26787844651355,
        "rangeM": 582.8220426184888,
        "pitchDeg": -59.997394702801266,
        "headingStartDeg": 349.99947886731456,
        "amplitudeDeg": 8,
        "periodS": 18,
        "law": "cosine"
      },
      "renditions": [
        {
          "src": "/landing/hero-desktop-2880-av1.ccee3faa.mp4",
          "mime": "video/mp4; codecs=\"av01.0.12M.08\"",
          "codec": "av1",
          "width": 2880,
          "height": 1800,
          "bytes": 15166856,
          "bitrateKbps": 6741
        },
        {
          "src": "/landing/hero-desktop-2880-hevc.4a936c94.mp4",
          "mime": "video/mp4; codecs=\"hvc1.1.6.L150.90\"",
          "codec": "hevc",
          "width": 2880,
          "height": 1800,
          "bytes": 14372555,
          "bitrateKbps": 6388
        },
        {
          "src": "/landing/hero-desktop-1920-av1.412872cf.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 1920,
          "height": 1200,
          "bytes": 8189946,
          "bitrateKbps": 3640
        },
        {
          "src": "/landing/hero-desktop-1920-h264.72f096f3.mp4",
          "mime": "video/mp4; codecs=\"avc1.640032\"",
          "codec": "h264",
          "width": 1920,
          "height": 1200,
          "bytes": 11436798,
          "bitrateKbps": 5083
        }
      ]
    },
    "phone": {
      "aspect": 0.461983,
      "fps": 30,
      "durationS": 18,
      "orbit": {
        "centerLat": 48.83258058872229,
        "centerLon": 2.264310755666521,
        "centerHeight": 95.2696329328622,
        "rangeM": 582.8200166586506,
        "pitchDeg": -59.99739471184423,
        "headingStartDeg": 349.9994788691313,
        "amplitudeDeg": 8,
        "periodS": 18,
        "law": "cosine"
      },
      "renditions": [
        {
          "src": "/landing/hero-phone-960-av1.ae2752c0.mp4",
          "mime": "video/mp4; codecs=\"av01.0.08M.08\"",
          "codec": "av1",
          "width": 960,
          "height": 2078,
          "bytes": 5966311,
          "bitrateKbps": 2652
        },
        {
          "src": "/landing/hero-phone-960-hevc.b9ab65cb.mp4",
          "mime": "video/mp4; codecs=\"hvc1.1.6.L120.90\"",
          "codec": "hevc",
          "width": 960,
          "height": 2078,
          "bytes": 5883802,
          "bitrateKbps": 2615
        }
      ]
    }
  }
});
