// GENERATED by `npm run landing:assets` (scripts/publish-landing-assets.mjs) from
// the capture's own record. Do not edit by hand: re-record instead.
//
// The recorded hero loops and the camera law each was filmed with, which
// src/vitrine/handoff.js evaluates at the video's clock.
export const HERO_LOOP = Object.freeze({
  "capturedAt": null,
  "videos": {
    "desktop": {
      "mp4": "/landing/hero-desktop.bf00841f.mp4",
      "width": 1600,
      "height": 900,
      "durationS": 18,
      "fps": 30,
      "orbit": {
        "centerLat": 48.83258065656644,
        "centerLon": 2.264310737545217,
        "centerHeight": 95.25636469202965,
        "rangeM": 582.8353379050097,
        "pitchDeg": -59.997394643349246,
        "headingStartDeg": 349.9994788554371,
        "amplitudeDeg": 8,
        "periodS": 18,
        "law": "cosine"
      }
    },
    "phone": {
      "mp4": "/landing/hero-phone.0f21e25f.mp4",
      "width": 780,
      "height": 1688,
      "durationS": 18,
      "fps": 30,
      "orbit": {
        "centerLat": 48.8325818614821,
        "centerLon": 2.2643104157098897,
        "centerHeight": 95.0207200481409,
        "rangeM": 583.1074440413616,
        "pitchDeg": -59.99739342691442,
        "headingStartDeg": 349.99947861207914,
        "amplitudeDeg": 8,
        "periodS": 18,
        "law": "cosine"
      }
    }
  }
});
